name: CI

on:
  push:
    branches:
      - '*'
#    tags:
#      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup keystores
        run: |
          if [[ -z "${{ secrets.DEBUG_KEYSTORE }}" ]]; then
            echo "WARNING: secrets.DEBUG_KEYSTORE is not defined"
          else
            echo "${{ secrets.DEBUG_KEYSTORE }}" > debug.keystore
          fi

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Environment info
        run: |
          gradle --version

      - name: build
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Environment info
        run: |
          gradle --version

      - uses: actions/upload-artifact@v2
        with:
          name: openimis-policies-apk-${{github.run_number}}-${{github.sha}}
          path: ./app/build/outputs/**/*.apk

      - name: build
        run: |
          ./gradlew bundleDebug --stacktrace

      - name: Environment info
        run: |
          gradle --version

      - uses: actions/upload-artifact@v2
        with:
          name: openimis-policies-aab-${{github.run_number}}-${{github.sha}}
          path: ./app/build/outputs/**/*.aab
